sudo: required
language: minimal
services:
  - docker

env:
 - IMAGE_PATH=wikibase/1.30/
 - IMAGE_PATH=wikibase/1.29/
 - IMAGE_PATH=wdqs/0.2.5/
 - IMAGE_PATH=wdqs/0.3.0/
 - IMAGE_PATH=wdqs-frontend/latest/
 - IMAGE_PATH=wdqs-proxy/latest/

script:
 - source ./.travis/docker-push-setup.sh
 - bash ./$IMAGE_PATH/.travis/build-deploy.sh

jobs:
  include:
    - stage: prebuild
      script: bash ./.travis/checkx.sh

stages:
  - prebuild
  - test
